package com.crmportal.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import com.crmportal.entity.AccountEntryEntity;
import com.crmportal.entity.CashAccountEntity;
import com.crmportal.response.dto.IncomeListResponseDto;

import java.time.LocalDate;
import java.util.List;
import java.util.Optional;


@Repository
public interface AccountEntryRepository extends JpaRepository<AccountEntryEntity, Long> {

	@Query(value = "SELECT voucher_no FROM account_entry " +
		       "WHERE voucher_no LIKE CONCAT(:prefix, '%') AND user_id = :userId AND is_delete = false " +
		       "ORDER BY id DESC LIMIT 1",
		       nativeQuery = true)
	String findLastVoucherByPrefix(@Param("prefix") String prefix, @Param("userId") Long userId);
	
	Optional<AccountEntryEntity> findByVoucherNoAndUserIdAndIsDeleteFalse(String voucherNo, Long userId);
	
	Optional<AccountEntryEntity> findByIdAndIsDeleteFalse(Long id);
	
//	@Query(
//		   " SELECT a FROM AccountEntryEntity a"
//		  + " WHERE (:entryType IS NULL OR a.entryType = :entryType)"
//		  + " AND (:accountType IS NULL OR a.accountType = :accountType)"
//		  + " AND (:paymentMode IS NULL OR a.paymentMode = :paymentMode)"
//		  + " AND (:cashTypeId IS NULL OR  :cashTypeId = -1l OR a.cashType.id = :cashTypeId)"
//		  + " AND (:bankAccountId IS NULL OR :bankAccountId = -1l OR a.bankDetails.id = :bankAccountId)"
//		  + " AND (:startDate IS NULL OR a.date >= :startDate)"
//		  + " AND (:endDate IS NULL OR a.date <= :endDate)"
//		  + " AND a.userId = :userId "
//		  + " AND a.isDelete = false"
//		)
//		List<AccountEntryEntity> findAllByFilters(
//		        @Param("entryType") EntryType entryType,
//		        @Param("accountType") AccountType accountType,
//		        @Param("paymentMode") PaymentMode paymentMode,
//		        @Param("cashTypeId") Long cashTypeId,
//		        @Param("bankAccountId") Long bankAccountId,
//		        @Param("startDate") LocalDate startDate,
//		        @Param("endDate") LocalDate endDate,
//		        @Param("userId") Long userId
//		);
	
	// account entry (cash/bank payment/receipt)
	@Query(value =
	        " SELECT "
	        + "    a.id, "
	        + "    a.user_id, "
	        + "    CAST(a.voucher_no AS CHAR) COLLATE utf8_unicode_ci AS voucher_no, "
	        + "    CAST(a.account_type AS CHAR) COLLATE utf8_unicode_ci AS account_type, "
	        + "    CAST(a.entry_type AS CHAR) COLLATE utf8_unicode_ci AS entry_type, "
	        + "    CAST(a.payment_mode AS CHAR) COLLATE utf8_unicode_ci AS payment_mode, "
	        + "    a.cash_account_id, "
	        + "    a.bank_account_id, "
	        + "    a.date AS entry_date, "
	        + "    CAST(a.account_contact_name AS CHAR) COLLATE utf8_unicode_ci AS party_name, "
	        + "    a.amount, "
	        + "    CAST(a.notes AS CHAR) COLLATE utf8_unicode_ci AS notes, "
	        + "    a.invoice_id, "
	        + "    CAST(a.reference_no AS CHAR) COLLATE utf8_unicode_ci AS reference_no, "
	        + "    a.is_delete, "
	        + "    a.created_at, "
	        + "    a.updated_at, "
	        + "    CAST('ACCOUNT ENTRY' AS CHAR) COLLATE utf8_unicode_ci AS source,"
	        + "    a.account_contact_id AS account_contact_id,"
	        + "    a.income_expense_type_id AS income_expense_type_id, "
	        + "    iet.name AS income_expense_type_name "
	        + " FROM account_entry a "
	        + " INNER JOIN income_expense_type iet on iet.type_id = a.income_expense_type_id "
	        + " WHERE (:entryType IS NULL OR a.entry_type = :entryType) "
	        + "   AND ( "
	        + "     ( :accountType = 'CASH' "
	        + "       AND a.payment_mode = 'CASH' "
	        + "       AND (:cashTypeId IS NOT NULL AND (:cashTypeId = -1 OR a.cash_account_id = :cashTypeId)) "
	        + "     ) "
	        + "     OR "
	        + "     ( :accountType = 'BANK' "
	        + "       AND a.payment_mode IN ('BANK_TRANSFER','UPI','CHEQUE') "
	        + "       AND ( "
	        + "            (:paymentMode IS NULL) "
	        + "            OR a.payment_mode = :paymentMode "
	        + "       ) "
	        + "       AND (:bankAccountId IS NOT NULL AND (:bankAccountId = -1 OR a.bank_account_id = :bankAccountId)) "
	        + "     ) "
	        + "   ) "
	        + "   AND (:startDate IS NULL OR a.date >= :startDate) "
	        + "   AND (:endDate IS NULL OR a.date <= :endDate) "
	        + "   AND a.user_id = :userId "
	        + "   AND a.is_delete = FALSE "
	        + " UNION ALL "
	        + " SELECT "
	        + "    ph.invoice_payment_id AS id, "
	        + "    CAST(1 AS SIGNED) AS user_id, "
	        + "    CAST(im.invoice_code AS CHAR) COLLATE utf8_unicode_ci AS voucher_no, "
	        + "    CASE WHEN ph.payment_mode = 'CASH' THEN CAST('CASH' AS CHAR) COLLATE utf8_unicode_ci ELSE CAST('BANK' AS CHAR) COLLATE utf8_unicode_ci END AS account_type, "
	        + "    CAST('RECEIPT' AS CHAR) COLLATE utf8_unicode_ci AS entry_type, "
	        + "    CAST(ph.payment_mode AS CHAR) COLLATE utf8_unicode_ci AS payment_mode, "
	        + "    ph.cash_type_id AS cash_account_id, "
	        + "    ph.bank_account_id, "
	        + "    ph.payment_date AS entry_date, "
	        + "    CAST(im.billing_name AS CHAR) COLLATE utf8_unicode_ci AS party_name, "
	        + "    ph.amount, "
	        + "    CAST('' AS CHAR) COLLATE utf8_unicode_ci AS notes, "
	        + "    im.invoice_id, "
	        + "    CAST(ph.transaction_id AS CHAR) COLLATE utf8_unicode_ci AS reference_no, "
	        + "    ph.is_delete, "
	        + "    ph.created_at, "
	        + "    ph.updated_at, "
	        + "    CAST('INVOICE PAYMENT' AS CHAR) COLLATE utf8_unicode_ci AS source, "
	        + "    im.customer_id AS account_contact_id,"
	        + "    CAST(-1 AS SIGNED) AS income_expense_type_id,"
	        + "    CAST('INV' AS CHAR) COLLATE utf8_unicode_ci AS income_expense_type_name "
	        + " FROM invoice_payment_history ph "
	        + " INNER JOIN invoice_master im ON ph.invoice_id = im.invoice_id "
	        + " WHERE "
	        + "   (:entryType IS NULL OR 'RECEIPT' = :entryType) "
	        + "   AND ( "
	        + "     ( :accountType = 'CASH' "
	        + "       AND ph.payment_mode = 'CASH' "
	        + "       AND (:cashTypeId IS NOT NULL AND (:cashTypeId = -1 OR ph.cash_type_id = :cashTypeId)) "
	        + "     ) "
	        + "     OR "
	        + "     ( :accountType = 'BANK' "
	        + "       AND ph.payment_mode IN ('BANK_TRANSFER','UPI','CHEQUE') "
	        + "       AND ( "
	        + "            :paymentMode IS NULL "
	        + "            OR ph.payment_mode = :paymentMode "
	        + "       ) "
	        + "       AND (:bankAccountId IS NOT NULL AND (:bankAccountId = -1 OR ph.bank_account_id = :bankAccountId)) "
	        + "     ) "
	        + "   ) "
	        + "   AND (:startDate IS NULL OR ph.payment_date >= :startDate) "
	        + "   AND (:endDate IS NULL OR ph.payment_date <= :endDate) "
	        + "   AND ph.is_delete = FALSE AND im.is_delete = FALSE "
	        + " UNION ALL "
	        + " SELECT "
	        + "    ph.trip_expense_id AS id, "
	        + "    e.user_id AS user_id, "
	        + "    CAST('EXP' AS CHAR) COLLATE utf8_unicode_ci AS voucher_no,  "
	        + "    CASE WHEN ph.payment_mode = 'CASH' THEN CAST('CASH' AS CHAR) COLLATE utf8_unicode_ci ELSE CAST('BANK' AS CHAR) COLLATE utf8_unicode_ci END AS account_type, "
	        + "    CAST('PAYMENT' AS CHAR) COLLATE utf8_unicode_ci AS entry_type, "
	        + "    CAST(ph.payment_mode AS CHAR) COLLATE utf8_unicode_ci AS payment_mode, "
	        + "    ph.cash_type_id AS cash_account_id, "
	        + "    ph.bank_account_id, "
	        + "    ph.payment_date AS entry_date, "
	        + "    CAST(ac.name AS CHAR) COLLATE utf8_unicode_ci AS party_name, "
	        + "    ph.amount, "
	        + "    CAST('' AS CHAR) COLLATE utf8_unicode_ci AS notes, "
	        + "    e.id, "
	        + "    CAST(ph.transaction_id AS CHAR) COLLATE utf8_unicode_ci AS reference_no, "
	        + "    ph.is_delete, "
	        + "    ph.created_at, "
	        + "    ph.updated_at, "
	        + "    CAST('TRIP EXPENSE' AS CHAR) COLLATE utf8_unicode_ci AS source, "
	        + "    CAST(-1 AS SIGNED) AS account_contact_id,"
	        + "    CAST(-1 AS SIGNED) AS income_expense_type_id, "
	        + "    CAST('' AS CHAR) COLLATE utf8_unicode_ci AS income_expense_type_name "
	        + " FROM trip_expense_payout_history ph   "
	        + " INNER JOIN expenses e ON ph.trip_expense_id = e.id AND e.user_id = :userId "
	        + " INNER JOIN account_contact ac ON "
	        + " ("
	        + "			("
	        + "    			ac.user_id = :userId "
	        + "    				AND EXISTS (  "
	        + "        			SELECT 1 FROM user_basic_details ubd "  
	        + "        			WHERE ubd.user_id = :userId  "
	        + "        			AND ubd.role_id IN (1, 2) "
	        + "    			)  "
	        + " 		)  "
	        + " 		OR (  "
	        + "    			ac.member_id = :userId "  
	        + "    			AND NOT EXISTS (  "
	        + "        		SELECT 1 FROM user_basic_details ubd "  
	        + "        		WHERE ubd.user_id = :userId  "
	        + "        		AND ubd.role_id IN (1, 2) "
	        + "    		)  "
	        + " 	 )"
	        + "	) "
	        + " WHERE "
	        + "   (:entryType IS NULL OR 'PAYMENT' = :entryType) "
	        + "   AND ( "
	        + "     ( :accountType = 'CASH' "
	        + "       AND ph.payment_mode = 'CASH' "
	        + "       AND (:cashTypeId IS NOT NULL AND (:cashTypeId = -1 OR ph.cash_type_id = :cashTypeId)) "
	        + "     ) "
	        + "     OR "
	        + "     ( :accountType = 'BANK' "
	        + "       AND ph.payment_mode IN ('BANK_TRANSFER','UPI','CHEQUE') "
	        + "       AND ( "
	        + "            :paymentMode IS NULL "
	        + "            OR ph.payment_mode = :paymentMode "
	        + "       ) "
	        + "       AND (:bankAccountId IS NOT NULL AND (:bankAccountId = -1 OR ph.bank_account_id = :bankAccountId)) "
	        + "     ) "
	        + "   ) "
	        + "   AND (:startDate IS NULL OR ph.payment_date >= :startDate) "
	        + "   AND (:endDate IS NULL OR ph.payment_date <= :endDate) "
	        + "   AND ph.is_delete = FALSE AND e.is_delete = FALSE "
	        + " UNION ALL "
	        + " SELECT "
	        + "    ph.office_expense_id AS id, "
	        + "    e.user_id AS user_id, "
	        + "    CAST('EXP' AS CHAR) COLLATE utf8_unicode_ci AS voucher_no, "
	        + "    CASE WHEN ph.payment_mode = 'CASH' THEN CAST('CASH' AS CHAR) COLLATE utf8_unicode_ci ELSE CAST('BANK' AS CHAR) COLLATE utf8_unicode_ci END AS account_type, "
	        + "    CAST('PAYMENT' AS CHAR) COLLATE utf8_unicode_ci AS entry_type, "
	        + "    CAST(ph.payment_mode AS CHAR) COLLATE utf8_unicode_ci AS payment_mode, "
	        + "    ph.cash_type_id AS cash_account_id, "
	        + "    ph.bank_account_id, "
	        + "    ph.payment_date AS entry_date, "
	        + "    CAST(ac.name AS CHAR) COLLATE utf8_unicode_ci AS party_name, "
	        + "    ph.amount, "
	        + "    CAST('' AS CHAR) COLLATE utf8_unicode_ci AS notes, "
	        + "    e.id, "
	        + "    CAST(ph.transaction_id AS CHAR) COLLATE utf8_unicode_ci AS reference_no, "
	        + "    ph.is_delete, "
	        + "    ph.created_at, "
	        + "    ph.updated_at, "
	        + "    CAST(CONCAT(UPPER(e.expense_type),' EXPENSE') AS CHAR) COLLATE utf8_unicode_ci AS source, "
	        + "    CAST(-1 AS SIGNED) AS account_contact_id,"
	        + "    CAST(-1 AS SIGNED) AS income_expense_type_id, "
	        + "    CAST(iet.name AS CHAR) COLLATE utf8_unicode_ci AS income_expense_type_name "
	        + " FROM office_expense_payout_history ph   "
	        + " INNER JOIN office_expenses e ON ph.office_expense_id = e.id AND e.user_id = :userId AND e.is_delete = FALSE "
	        + " INNER JOIN income_expense_type iet ON iet.type_id = e.income_expense_type_id "
	        + " INNER JOIN account_contact ac ON "
	        + " ("
	        + "			("
	        + "    			ac.user_id = :userId "
	        + "    				AND EXISTS (  "
	        + "        			SELECT 1 FROM user_basic_details ubd "  
	        + "        			WHERE ubd.user_id = :userId  "
	        + "        			AND ubd.role_id IN (1, 2) "
	        + "    			)  "
	        + " 		)  "
	        + " 		OR (  "
	        + "    			ac.member_id = :userId "  
	        + "    			AND NOT EXISTS (  "
	        + "        		SELECT 1 FROM user_basic_details ubd "  
	        + "        		WHERE ubd.user_id = :userId  "
	        + "        		AND ubd.role_id IN (1, 2) "
	        + "    		)  "
	        + " 	 )"
	        + "	) "
	        + " WHERE "
	        + "   (:entryType IS NULL OR 'PAYMENT' = :entryType) "
	        + "   AND ( "
	        + "     ( :accountType = 'CASH' "
	        + "       AND ph.payment_mode = 'CASH' "
	        + "       AND (:cashTypeId IS NOT NULL AND (:cashTypeId = -1 OR ph.cash_type_id = :cashTypeId)) "
	        + "     ) "
	        + "     OR "
	        + "     ( :accountType = 'BANK' "
	        + "       AND ph.payment_mode IN ('BANK_TRANSFER','UPI','CHEQUE') "
	        + "       AND ( "
	        + "            :paymentMode IS NULL "
	        + "            OR ph.payment_mode = :paymentMode "
	        + "       ) "
	        + "       AND (:bankAccountId IS NOT NULL AND (:bankAccountId = -1 OR ph.bank_account_id = :bankAccountId)) "
	        + "     ) "
	        + "   ) "
	        + "   AND (:startDate IS NULL OR ph.payment_date >= :startDate) "
	        + "   AND (:endDate IS NULL OR ph.payment_date <= :endDate) "
	        + "   AND ph.is_delete = FALSE "
	        + " ORDER BY entry_date DESC, created_at DESC ",
	        nativeQuery = true)
	List<Object[]> findAllDataByFilters (
	        String entryType,
	        String accountType,
	        String paymentMode,
	        Long cashTypeId,
	        Long bankAccountId,
	        String startDate,
	        String endDate,
	        Long userId
	);
	
	// cash/bank book
	@Query(value =
	        "SELECT  "
	        + "	data.payment_date, "
	        + "	data.voucher_no, "
	        + "	data.particular, "
	        + "	data.debit, "
	        + "	data.credit "
	        + "FROM ( "
	        + "	    SELECT "
	        + "		0 AS sort_order, "
	        + "		CAST(:startDate AS DATE) AS payment_date, "
	        + "		'-' AS voucher_no, "
	        + "		CAST('OPB/PREV' AS CHAR) COLLATE utf8_unicode_ci AS particular, "
	        + "		IFNULL(CASE WHEN SUM(x.debit - x.credit) >= 0 THEN SUM(x.debit - x.credit) ELSE 0 END, 0) AS debit, "
	        + "		IFNULL(CASE WHEN SUM(x.debit - x.credit) < 0 THEN ABS(SUM(x.debit - x.credit)) ELSE 0 END, 0) AS credit "
	        + "	    FROM ( "
	        + "		SELECT  "
	        + "		    iph.payment_date AS DATE, "
	        + "		    iph.amount AS debit, "
	        + "		    0 AS credit "
	        + "		FROM invoice_payment_history iph "
	        + "		WHERE iph.is_delete = FALSE "
	        + " 	  AND :userId = 1 "
	        + "		  AND ( "
	        + "    		(:accountType = 'CASH' "
	        + "        		AND iph.payment_mode = 'CASH' "
	        + "        		AND (:cashTypeId IS NOT NULL AND (:cashTypeId = -1 OR iph.cash_type_id = :cashTypeId)) "
	        + "    		) "
	        + "   		OR "
	        + "    		(:accountType = 'BANK' "
	        + "       		AND iph.payment_mode IN ('BANK_TRANSFER','UPI','CHEQUE') "
	        + "        		AND (:paymentMode IS NULL OR iph.payment_mode = :paymentMode) "
	        + "        		AND (:bankAccountId IS NOT NULL AND (:bankAccountId = -1 OR iph.bank_account_id = :bankAccountId)) "
	        + "    		) "
	        + "		  ) "
	        + "		  AND iph.payment_date < :startDate "
	        + " "
	        + "		UNION ALL "
	        + " "
	        + "		SELECT  "
	        + "		    CAST(te.payment_date AS DATE) AS DATE, "
	        + "		    0 AS debit, "
	        + "		    te.amount AS credit "
	        + "		FROM trip_expense_payout_history te "
	        + " 	INNER JOIN expenses e ON e.id = te.trip_expense_id "
	        + "		WHERE te.is_delete = FALSE "
	        + "		  AND ( "
	        + "    		(:accountType = 'CASH' "
	        + "        		AND te.payment_mode = 'CASH' "
	        + "        		AND (:cashTypeId IS NOT NULL AND (:cashTypeId = -1 OR te.cash_type_id = :cashTypeId)) "
	        + "    		) "
	        + "    	    OR "
	        + "    		(:accountType = 'BANK' "
	        + "        		AND te.payment_mode IN ('BANK_TRANSFER','UPI','CHEQUE') "
	        + "        		AND (:paymentMode IS NULL OR te.payment_mode = :paymentMode) "
	        + "        		AND (:bankAccountId IS NOT NULL AND (:bankAccountId = -1 OR te.bank_account_id = :bankAccountId)) "
	        + "    		) "
	        + "		  ) "
	        + "		  AND te.payment_date < :startDate"
	        + "		  AND e.user_id = :userId"
	        + " 	  AND e.is_delete = FALSE "
	        + " "
	        + "		UNION ALL "
	        + " "
	        + "		SELECT  "
	        + "		    CAST(op.payment_date AS DATE) AS DATE, "
	        + "		    0 AS debit, "
	        + "		    op.amount AS credit "
	        + "		FROM office_expense_payout_history op "
	        + " 	INNER JOIN office_expenses oe ON op.office_expense_id = oe.id "
	        + "		WHERE op.is_delete = FALSE "
	        + "		  AND ( "
	        + "    		(:accountType = 'CASH' "
	        + "        		AND op.payment_mode = 'CASH' "
	        + "        		AND (:cashTypeId IS NOT NULL AND (:cashTypeId = -1 OR op.cash_type_id = :cashTypeId)) "
	        + "    		) "
	        + "    	    OR "
	        + "    		(:accountType = 'BANK' "
	        + "        		AND op.payment_mode IN ('BANK_TRANSFER','UPI','CHEQUE') "
	        + "        		AND (:paymentMode IS NULL OR op.payment_mode = :paymentMode) "
	        + "        		AND (:bankAccountId IS NOT NULL AND (:bankAccountId = -1 OR op.bank_account_id = :bankAccountId)) "
	        + "    		) "
	        + "		  ) "
	        + "		  AND op.payment_date < :startDate "
	        + " 	  AND oe.is_delete = FALSE "
	        + " 	  AND oe.user_id = :userId "
	        + " "
	        + "		UNION ALL "
	        + " "
	        + "		SELECT  "
	        + "		    CAST(ae.date AS DATE) AS DATE, "
	        + "		    CASE WHEN ae.entry_type = 'RECEIPT' THEN ae.amount ELSE 0 END AS debit, "
	        + "		    CASE WHEN ae.entry_type = 'PAYMENT' THEN ae.amount ELSE 0 END AS credit "
	        + "		FROM account_entry ae "
	        + "		WHERE ae.is_delete = FALSE "
	        + "  	  AND :userId = 1 "
	        + "		  AND ( "
	        + "    		(:accountType = 'CASH' "
	        + "        		AND ae.payment_mode = 'CASH' "
	        + "        		AND (:cashTypeId IS NOT NULL AND (:cashTypeId = -1 OR ae.cash_account_id = :cashTypeId)) "
	        + "   		) "
	        + "    		OR "
	        + "    		(:accountType = 'BANK' "
	        + "        		AND ae.payment_mode IN ('BANK_TRANSFER','UPI','CHEQUE') "
	        + "        		AND (:paymentMode IS NULL OR ae.payment_mode = :paymentMode) "
	        + "        		AND (:bankAccountId IS NOT NULL AND (:bankAccountId = -1 OR ae.bank_account_id = :bankAccountId)) "
	        + "    		) "
	        + "		  ) "
	        + "		  AND ae.date < :startDate "
	        + " "
	        + "  	UNION ALL"
	        + " "
	        + "  	SELECT"
	        + "		    si.payment_date AS DATE, "
	        + "		    si.total_amount AS debit, "
	        + "		    0 AS credit "
	        + " 	FROM sales_invoice si"
	        + " 	WHERE si.is_delete = FALSE "
	        + " 	AND :userId != 1"
	        + "		AND ( "
	        + "    			(:accountType = 'CASH' "
	        + "        			AND si.payment_mode = 'CASH' "
	        + "        			AND (:cashTypeId IS NOT NULL AND (:cashTypeId = -1 OR si.cash_id = :cashTypeId)) "
	        + "   			) "
	        + "    			OR "
	        + "    			(:accountType = 'BANK' "
	        + "        			AND si.payment_mode IN ('BANK_TRANSFER','UPI','CHEQUE') "
	        + "        			AND (:paymentMode IS NULL OR si.payment_mode = :paymentMode) "
	        + "        			AND (:bankAccountId IS NOT NULL AND (:bankAccountId = -1 OR si.bank_id = :bankAccountId)) "
	        + "    			) "
	        + "		 	 ) "
	        + "		AND si.payment_date < :startDate "
	        + " "
	        + "  	UNION ALL"
	        + " "
	        + "  	SELECT"
	        + "		    vp.payment_date AS DATE, "
	        + "		    COALESCE(vp.received_amount, 0) AS debit, "
	        + "		    COALESCE(vp.pay_amount, 0) AS credit "
	        + " 	FROM vendor_payments vp"
	        + " 	WHERE  "
	        + " 	(:userId != 1 AND vp.user_id = :userId)"
	        + "		AND ( "
	        + "    			(:accountType = 'CASH' "
	        + "        			AND vp.payment_mode = 'CASH' "
	        + "        			AND (:cashTypeId IS NOT NULL AND (:cashTypeId = -1 OR vp.cash_account_id = :cashTypeId)) "
	        + "   			) "
	        + "    			OR "
	        + "    			(:accountType = 'BANK' "
	        + "        			AND vp.payment_mode IN ('BANK_TRANSFER','UPI','CHEQUE', 'BANK TRANSFER') "
	        + "        			AND (:paymentMode IS NULL OR vp.payment_mode = :paymentMode) "
	        + "        			AND (:bankAccountId IS NOT NULL AND (:bankAccountId = -1 OR vp.bank_id = :bankAccountId)) "
	        + "    			) "
	        + "		 	 ) "
	        + " 	AND vp.is_delete = FALSE "
	        + " 	AND vp.payment_date < :startDate "
	        + " "
	        + " 	UNION ALL "
	        + ""
	        + "		SELECT "
	        + "    		at.date, "
	        + "    		CASE "
	        + "        		WHEN :accountType = 'CASH' "
	        + "             	AND at.to_type = 'CASH' "
	        + "            		AND (:cashTypeId = -1 OR at.to_account_id = :cashTypeId) "
	        + "        		THEN at.amount "
	        + "        		WHEN :accountType = 'BANK' "
	        + "            		AND at.to_type = 'BANK' "
	        + "            		AND (:bankAccountId = -1 OR at.to_account_id = :bankAccountId) "
	        + "    	  		THEN at.amount "
	        + "        		ELSE 0 "
	        + "    		END AS debit,"
	        + "    		CASE "
	        + "        		WHEN :accountType = 'CASH'"
	        + "             	AND at.from_type = 'CASH'"
	        + "             	AND (:cashTypeId = -1 OR at.from_account_id = :cashTypeId)"
	        + "        		THEN at.amount "
	        + "        		WHEN :accountType = 'BANK'"
	        + "             	AND at.from_type = 'BANK'"
	        + "             	AND (:bankAccountId = -1 OR at.from_account_id = :bankAccountId)"
	        + "        		THEN at.amount"
	        + "        		ELSE 0 "
	        + "    		END AS credit "
	        + "		FROM amount_transfer at"
	        + "		WHERE at.is_delete = FALSE"
	        + "		AND at.user_id = :userId"
	        + "		AND at.date < :startDate"
	        + " "
	        + "  	UNION ALL"
	        + "	"
	        + " 	SELECT  "
	        + "     	CAST(:startDate AS DATE) AS DATE, "
	        + "     	SUM(CASE WHEN opening_balance >= 0 THEN opening_balance ELSE 0 END) AS debit, "
	        + "     	SUM(CASE WHEN opening_balance < 0 THEN ABS(opening_balance) ELSE 0 END) AS credit "
	        + " 		FROM ( "
	        + "     		SELECT ca.opening_balance "
	        + "     		FROM cash_account ca "
	        + "     		WHERE :accountType = 'CASH' "
	        + "       			AND (:cashTypeId = -1 OR ca.id = :cashTypeId) "
	        + " 				AND ca.user_id = :userId "
	        + " "
	        + "     	UNION ALL "
	        + " "
	        + "     	SELECT bd.opening_balance "
	        + "    		FROM bank_details bd "
	        + "     	WHERE :accountType = 'BANK' "
	        + "       	AND (:bankAccountId = -1 OR bd.id = :bankAccountId) "
	        + " 		AND bd.user_id = :userId "
	        + " 	) ob"
	        + "		) x "
	        + "	 "
	        + "		 "
	        + "	UNION ALL "
	        + "	 "
	        + "	SELECT "
	        + "		1 AS sort_order, "
	        + "		CAST(ph.payment_date AS DATE) AS payment_date, "
	        + "		CAST(im.invoice_code AS CHAR) COLLATE utf8_unicode_ci AS 'voucher_no', "
	        + "		CAST('INVOICE PAYMENT' AS CHAR) COLLATE utf8_unicode_ci AS particulars, "
	        + "		ph.amount AS debit, "
	        + "		0 AS credit "
	        + "	FROM "
	        + "		invoice_payment_history ph "
	        + "		INNER JOIN invoice_master im ON ph.invoice_id = im.invoice_id "
	        + "	WHERE "
	        + " 	:userId = 1 "
	        + "   	AND "
	        + " 	( "
	        + "     	( :accountType = 'CASH' "
	        + "       		AND ph.payment_mode = 'CASH' "
	        + "       		AND (:cashTypeId IS NOT NULL AND (:cashTypeId = -1 OR ph.cash_type_id = :cashTypeId)) "
	        + "     	) "
	        + "      	OR "
	        + "     	( :accountType = 'BANK' "
	        + "       		AND ph.payment_mode IN ('BANK_TRANSFER','UPI','CHEQUE') "
	        + "       		AND ( "
	        + "        	    	:paymentMode IS NULL "
	        + "        	    	OR ph.payment_mode = :paymentMode "
	        + "       		) "
	        + "       		AND (:bankAccountId IS NOT NULL AND (:bankAccountId = -1 OR ph.bank_account_id = :bankAccountId)) "
	        + "     	) "
	        + "   	)"
	        + "		AND ph.is_delete = FALSE "
	        + "		AND im.is_delete = FALSE "
	        + "     AND ph.payment_date >= :startDate "
	        + "		AND ph.payment_date <= :endDate "
	        + "	 "
	        + "	UNION ALL "
	        + "		 "
	        + "	SELECT "
	        + "		1 AS sort_order, "
	        + "		CAST(te.payment_date AS DATE) AS payment_date, "
	        + "		CAST('' AS CHAR) COLLATE utf8_unicode_ci AS 'voucher_no', "
	        + "		CAST('TRIP EXPENSE' AS CHAR) COLLATE utf8_unicode_ci AS particulars, "
	        + "		0 AS debit, "
	        + "		te.amount AS credit "
	        + "	FROM  "
	        + "		trip_expense_payout_history te "
	        + "		INNER JOIN expenses e ON te.trip_expense_id = e.id "
	        + "	WHERE "
	        + "   	( "
	        + "     	( :accountType = 'CASH' "
	        + "       		AND te.payment_mode = 'CASH' "
	        + "       		AND (:cashTypeId IS NOT NULL AND (:cashTypeId = -1 OR te.cash_type_id = :cashTypeId)) "
	        + "     	) "
	        + "      	OR "
	        + "     	( :accountType = 'BANK' "
	        + "       		AND te.payment_mode IN ('BANK_TRANSFER','UPI','CHEQUE') "
	        + "       		AND ( "
	        + "        	    	:paymentMode IS NULL "
	        + "        	    	OR te.payment_mode = :paymentMode "
	        + "       		) "
	        + "       		AND (:bankAccountId IS NOT NULL AND (:bankAccountId = -1 OR te.bank_account_id = :bankAccountId)) "
	        + "     	) "
	        + "   	) "
	        + "		AND te.is_delete = FALSE  "
	        + "		AND e.is_delete = FALSE "
	        + "     AND te.payment_date >= :startDate "
	        + "		AND te.payment_date <= :endDate "
	        + " 	AND e.user_id = :userId "
	        + "		 "
	        + "	UNION ALL "
	        + "		 "
	        + "	SELECT  "
	        + "		1 AS sort_order, "
	        + "		CAST(op.payment_date AS DATE) AS payment_date, "
	        + "		CAST('' AS CHAR) COLLATE utf8_unicode_ci AS 'voucher_no', "
	        + "		CAST(CONCAT(UPPER(iet.name),' EXPENSE') AS CHAR) COLLATE utf8_unicode_ci AS particulars, "
	        + "		0 AS debit, "
	        + "		op.amount AS credit "
	        + "	FROM  "
	        + "		office_expense_payout_history op "
	        + "		INNER JOIN office_expenses e ON op.office_expense_id = e.id "
	        + "		INNER JOIN income_expense_type iet ON iet.type_id = e.income_expense_type_id "
	        + "	WHERE "
	        + "   	( "
	        + "     	( :accountType = 'CASH' "
	        + "       		AND op.payment_mode = 'CASH' "
	        + "       		AND (:cashTypeId IS NOT NULL AND (:cashTypeId = -1 OR op.cash_type_id = :cashTypeId)) "
	        + "     	) "
	        + "      	OR "
	        + "     	( :accountType = 'BANK' "
	        + "       		AND op.payment_mode IN ('BANK_TRANSFER','UPI','CHEQUE') "
	        + "       		AND ( "
	        + "        	    	:paymentMode IS NULL "
	        + "        	    	OR op.payment_mode = :paymentMode "
	        + "       		) "
	        + "       		AND (:bankAccountId IS NOT NULL AND (:bankAccountId = -1 OR op.bank_account_id = :bankAccountId)) "
	        + "     	) "
	        + "   	) "
	        + "		AND op.is_delete = FALSE  "
	        + "		AND e.is_delete = FALSE "
	        + "     AND op.payment_date >= :startDate "
	        + "		AND op.payment_date <= :endDate "
	        + " 	AND e.user_id = :userId "
	        + "		 "
	        + "	UNION ALL "
	        + "	 "
	        + "	SELECT "
	        + "		1 AS sort_order, "
	        + "		CAST(ae.date AS DATE) AS payment_date, "
	        + "		CAST(ae.voucher_no AS CHAR) COLLATE utf8_unicode_ci AS 'voucher_no', "
	        + "		CAST('ACCOUNT ENTRY' AS CHAR) COLLATE utf8_unicode_ci AS particulars, "
	        + "		CASE WHEN ae.entry_type = 'RECEIPT' THEN ae.amount ELSE 0 END AS debit, "
	        + "		CASE WHEN ae.entry_type = 'PAYMENT' THEN ae.amount ELSE 0 END AS credit "
	        + "	FROM  "
	        + "		account_entry ae "
	        + "	WHERE "
	        + " 	:userId = 1 "
	        + " 	AND "
	        + "   	( "
	        + "     	( :accountType = 'CASH' "
	        + "       		AND ae.payment_mode = 'CASH' "
	        + "       		AND (:cashTypeId IS NOT NULL AND (:cashTypeId = -1 OR ae.cash_account_id = :cashTypeId)) "
	        + "     	) "
	        + "      	OR "
	        + "     	( :accountType = 'BANK' "
	        + "       		AND ae.payment_mode IN ('BANK_TRANSFER','UPI','CHEQUE') "
	        + "       		AND ( "
	        + "        	    	:paymentMode IS NULL "
	        + "        	    	OR ae.payment_mode = :paymentMode "
	        + "       		) "
	        + "       		AND (:bankAccountId IS NOT NULL AND (:bankAccountId = -1 OR ae.bank_account_id = :bankAccountId)) "
	        + "     	) "
	        + "   	) "
	        + "		AND ae.is_delete = FALSE "
	        + "     AND ae.date >= :startDate "
	        + "		AND ae.date <= :endDate "
	        + "	"
	        + " UNION ALL "
	        + "  "
	        + "  SELECT "
	        + "	 1 AS sort_order, "
	        + "  CAST(vp.payment_date AS DATE) AS payment_date, "
	        + "  CAST(vp.invoice_code AS CHAR) COLLATE utf8_unicode_ci AS 'voucher_no', "
	        + "  COALESCE(ac.name,p.name_english) COLLATE utf8_unicode_ci AS particulars, "
	        + "  COALESCE(vp.received_amount, 0) AS debit, "
	        + "  COALESCE(vp.pay_amount,0) AS credit "
	        + "  FROM vendor_payments vp LEFT JOIN account_contact ac ON vp.vendor_id = ac.account_contact_id "
	        + "  LEFT JOIN partymaster p ON vp.vendor_id = p.party_id  WHERE vp.user_id = :userId "
	        + "   	AND "
	        + " 	( "
	        + "     	( :accountType = 'CASH' "
	        + "       		AND vp.payment_mode = 'CASH' "
	        + "       		AND (:cashTypeId IS NOT NULL AND (:cashTypeId = -1 OR vp.cash_account_id = :cashTypeId)) "
	        + "     	) "
	        + "      	OR "
	        + "     	( :accountType = 'BANK' "
	        + "       		AND vp.payment_mode IN ('BANK_TRANSFER','UPI','CHEQUE','BANK TRANSFER') "
	        + "       		AND ( "
	        + "        	    	:paymentMode IS NULL "
	        + "        	    	OR vp.payment_mode = :paymentMode "
	        + "       		) "
	        + "       		AND (:bankAccountId IS NOT NULL AND (:bankAccountId = -1 OR vp.bank_id = :bankAccountId)) "
	        + "     	) "
	        + "   	)"
	        + "		AND vp.is_delete = FALSE "
	        + "     AND vp.payment_date >= :startDate "
	        + "		AND vp.payment_date <= :endDate "
	        + "  "
	        + " UNION ALL "
	        + "	"
	        + "	SELECT "
	        + "		1 AS sort_order, "
	        + "		CAST(si.payment_date AS DATE) AS payment_date, "
	        + "		CAST(ei.invoice_code AS CHAR) COLLATE utf8_unicode_ci AS 'voucher_no', "
	        + "		CAST('INVOICE PAYMENT' AS CHAR) COLLATE utf8_unicode_ci AS particulars, "
	        + "		si.total_amount AS debit, "
	        + "		0 AS credit "
	        + "	FROM "
	        + " 	sales_invoice si "
	        + " 	INNER JOIN event_invoice ei ON si.invoice_no = ei.invoice_code "
	        + " WHERE "
	        + " 	(:userId != 1 AND ei.user_id = :userId)"
	        + "   	AND "
	        + " 	( "
	        + "     	( :accountType = 'CASH' "
	        + "       		AND si.payment_mode = 'CASH' "
	        + "       		AND (:cashTypeId IS NOT NULL AND (:cashTypeId = -1 OR si.cash_id = :cashTypeId)) "
	        + "     	) "
	        + "      	OR "
	        + "     	( :accountType = 'BANK' "
	        + "       		AND si.payment_mode IN ('BANK_TRANSFER','UPI','CHEQUE') "
	        + "       		AND ( "
	        + "        	    	:paymentMode IS NULL "
	        + "        	    	OR si.payment_mode = :paymentMode "
	        + "       		) "
	        + "       		AND (:bankAccountId IS NOT NULL AND (:bankAccountId = -1 OR si.bank_id = :bankAccountId)) "
	        + "     	) "
	        + "   	)"
	        + "		AND si.is_delete = FALSE "
	        + "		AND ei.is_delete = FALSE "
	        + "     AND si.payment_date >= :startDate "
	        + "		AND si.payment_date <= :endDate "
	        + " "
	        + "UNION ALL"
	        + ""
	        + " SELECT"
	        + "     1 AS sort_order,"
	        + "     CAST(at.date AS DATE) AS payment_date,"
	        + "     '' AS voucher_no,"
	        + "     CASE"
	        + "         WHEN at.from_type='CASH' AND at.to_type='BANK'"
	        + "             THEN 'CASH TO BANK TRANSFER'"
	        + "         WHEN at.from_type='BANK' AND at.to_type='CASH'"
	        + "             THEN 'BANK TO CASH TRANSFER'"
	        + "         WHEN at.from_type='CASH' AND at.to_type='CASH'"
	        + "             THEN 'CASH TO CASH TRANSFER'"
	        + "         WHEN at.from_type='BANK' AND at.to_type='BANK'"
	        + "             THEN 'BANK TO BANK TRANSFER'"
	        + "     END AS particular,"
	        + "     CASE"
	        + "         WHEN :accountType='CASH'"
	        + "              AND at.to_type='CASH'"
	        + "              AND (:cashTypeId=-1 OR at.to_account_id=:cashTypeId)"
	        + "         THEN at.amount"
	        + "         WHEN :accountType='BANK'"
	        + "              AND at.to_type='BANK'"
	        + "              AND (:bankAccountId=-1 OR at.to_account_id=:bankAccountId)"
	        + "         THEN at.amount"
	        + "         ELSE 0"
	        + "     END AS debit,"
	        + "     CASE"
	        + "         WHEN :accountType='CASH'"
	        + "              AND at.from_type='CASH'"
	        + "              AND (:cashTypeId=-1 OR at.from_account_id=:cashTypeId)"
	        + "         THEN at.amount"
	        + "         WHEN :accountType='BANK'"
	        + "              AND at.from_type='BANK'"
	        + "              AND (:bankAccountId=-1 OR at.from_account_id=:bankAccountId)"
	        + "         THEN at.amount"
	        + "         ELSE 0"
	        + "     END AS credit"
	        + " FROM amount_transfer at"
	        + " WHERE at.is_delete = FALSE"
	        + " AND at.user_id = :userId"
	        + " AND at.date BETWEEN :startDate AND :endDate"
	        + " AND ("
	        + "         (:accountType='CASH'"
	        + "             AND ("
	        + "                     (at.from_type='CASH'"
	        + "                         AND (:cashTypeId=-1 OR at.from_account_id=:cashTypeId))"
	        + "                  OR (at.to_type='CASH'"
	        + "                         AND (:cashTypeId=-1 OR at.to_account_id=:cashTypeId))"
	        + "             )"
	        + "         )"
	        + "      OR"
	        + "         (:accountType='BANK'"
	        + "             AND ("
	        + "                     (at.from_type='BANK'"
	        + "                         AND (:bankAccountId=-1 OR at.from_account_id=:bankAccountId))"
	        + "                  OR (at.to_type='BANK'"
	        + "                         AND (:bankAccountId=-1 OR at.to_account_id=:bankAccountId))"
	        + "             )"
	        + "         )"
	        + " ) "
	        + " ) data "
	        + " ORDER BY data.sort_order ASC, data.payment_date ASC ",
	        nativeQuery = true)
	List<Object[]> getAccountLedgerWithOpb(
	        @Param("startDate") String startDate,
	        @Param("endDate") String endDate,
	        @Param("accountType") String accountType,
	        @Param("paymentMode") String paymentMode,
	        @Param("cashTypeId") Long cashTypeId,
	        @Param("bankAccountId") Long bankAccountId,
	        @Param("userId") Long userId
	);
	
 	List<AccountEntryEntity> findAllByCashTypeAndIsDeleteFalse(CashAccountEntity cashType);
 	
 	// income list
 	@Query(value = "SELECT  "
 			+ " 	a.account_contact_name COLLATE utf8_unicode_ci AS `name`, "
 			+ "	 	a.id AS record_id, "
 			+ "	 	a.voucher_no COLLATE utf8_unicode_ci AS voucher_no, "
 			+ "	 	a.amount, "
 			+ "	 	a.created_at AS `date`, "
 			+ "	 	a.payment_mode COLLATE utf8_unicode_ci AS payment_mode "
 			+ "	FROM account_entry a "
 			+ "		INNER JOIN income_expense_type ie ON a.income_expense_type_id = ie.type_id "
 			+ "		WHERE a.entry_type = 'RECEIPT' "
 			+ "		AND :userId = 1 "
 			+ "		AND (:startDate IS NULL OR a.date >= STR_TO_DATE(:startDate, '%d/%m/%Y')) "
 			+ "		AND (:endDate IS NULL OR a.date <= STR_TO_DATE(:endDate, '%d/%m/%Y')) "
 			+ "		AND (:typeId IS NULL OR ie.type_id = :typeId) "
 			+ "		AND ie.is_delete = FALSE "
 			+ "		AND a.is_delete = FALSE"
 			+ "   	AND "
 			+ " 	(:accountType IS NULL OR ( "
	        + "     	( :accountType = 'CASH' "
	        + "       		AND a.payment_mode = 'CASH' "
	        + "       		AND (:cashAccountId IS NOT NULL AND (:cashAccountId = -1 OR a.cash_account_id = :cashAccountId)) "
	        + "     	) "
	        + "      	OR "
	        + "     	( :accountType = 'BANK' "
	        + "       		AND a.payment_mode IN ('BANK_TRANSFER','UPI','CHEQUE') "
	        + "       		AND ( "
	        + "        	    	:paymentMode IS NULL "
	        + "        	    	OR a.payment_mode = :paymentMode "
	        + "       		) "
	        + "       		AND (:bankAccountId IS NOT NULL AND (:bankAccountId = -1 OR a.bank_account_id = :bankAccountId)) "
	        + "     	) "
	        + "   	)) "
 			+ "UNION ALL "
 			+ "	SELECT  "
 			+ "		im.billing_name COLLATE utf8_unicode_ci AS `name`, "
 			+ "		iph.invoice_payment_id AS record_id, "
 			+ "		im.invoice_code COLLATE utf8_unicode_ci AS voucher_no, "
 			+ "		iph.amount AS amount, "
 			+ "		iph.payment_date AS `date`, "
 			+ "		iph.payment_mode COLLATE utf8_unicode_ci AS payment_mode "
 			+ " FROM invoice_payment_history iph "
 			+ "		INNER JOIN invoice_master im ON iph.invoice_id = im.invoice_id "
 			+ "		WHERE :typeId IS NULL "
 			+ " 	AND :userId = 1 "
 			+ " 	AND iph.is_delete = FALSE "
 			+ "		AND im.is_delete = FALSE "
 			+ "		AND (:startDate IS NULL OR iph.payment_date >= STR_TO_DATE(:startDate, '%d/%m/%Y')) "
 			+ "		AND (:endDate IS NULL OR iph.payment_date <= STR_TO_DATE(:endDate, '%d/%m/%Y')) "
 			+ "   	AND "
 			+ " 	(:accountType IS NULL OR ( "
	        + "     	( :accountType = 'CASH' "
	        + "       		AND iph.payment_mode = 'CASH' "
	        + "       		AND (:cashAccountId IS NOT NULL AND (:cashAccountId = -1 OR iph.cash_type_id = :cashAccountId)) "
	        + "     	) "
	        + "      	OR "
	        + "     	( :accountType = 'BANK' "
	        + "       		AND iph.payment_mode IN ('BANK_TRANSFER','UPI','CHEQUE') "
	        + "       		AND ( "
	        + "        	    	:paymentMode IS NULL "
	        + "        	    	OR iph.payment_mode = :paymentMode "
	        + "       		) "
	        + "       		AND (:bankAccountId IS NOT NULL AND (:bankAccountId = -1 OR iph.bank_account_id = :bankAccountId)) "
	        + "     	) "
	        + "   	))"
	        + "UNION ALL "
	        + " SELECT  "
	        + "		ei.billingname COLLATE utf8_unicode_ci AS `name`, "
	        + "		si.id AS record_id, "
	        + "		ei.invoice_code COLLATE utf8_unicode_ci AS voucher_no, "
	        + "		si.total_amount AS amount, "
	        + "		si.payment_date AS `date`, "
	        + "		si.payment_mode COLLATE utf8_unicode_ci AS payment_mode  "
	        + "	FROM sales_invoice si "
	        + "		INNER JOIN event_invoice ei ON si.invoice_no = ei.invoice_code "
	        + "		WHERE (:userId != 1 AND ei.user_id = :userId)"
	        + "		AND ei.is_delete = FALSE "
	        + "		AND si.is_delete = FALSE"
	        + "		AND (:startDate IS NULL OR si.payment_date >= STR_TO_DATE(:startDate, '%d/%m/%Y'))"
	        + "		AND (:endDate IS NULL OR si.payment_date <= STR_TO_DATE(:endDate, '%d/%m/%Y'))"
	        + "   	AND "
	        + "		(:accountType IS NULL OR ( "
	        + "     	( :accountType = 'CASH' "
	        + "       		AND UPPER(si.payment_mode) = 'CASH' "
	        + "       		AND (:cashAccountId IS NOT NULL AND (:cashAccountId = -1 OR si.cash_id = :cashAccountId)) "
	        + "     	) "
	        + "      	OR "
	        + "     	( :accountType = 'BANK' "
	        + "       		AND si.payment_mode IN ('BANK_TRANSFER','UPI','CHEQUE') "
	        + "       		AND ( "
	        + "        	    	:paymentMode IS NULL "
	        + "        	    	OR si.payment_mode = :paymentMode "
	        + "       		) "
	        + "       		AND (:bankAccountId IS NOT NULL AND (:bankAccountId = -1 OR si.bank_id = :bankAccountId)) "
	        + "     	) "
	        + "   	))"
 			+ " "
 			+ "ORDER BY `date` DESC; ",
 			nativeQuery = true)
 	List<Object[]> getAllIncomeData(
 			@Param("accountType") String accountType,
 			@Param("paymentMode") String paymentMode,
 			@Param("cashAccountId") Long cashAccountId,
 			@Param("bankAccountId") Long bankAccountId,
 			@Param("typeId") Long typeId,
 			@Param("startDate") String startDate,
 			@Param("endDate") String endDate,
 			@Param("userId") Long userId);
 	
 	List<AccountEntryEntity> findAllByUserIdAndDateBetweenAndIsDeleteFalse(Long userId, LocalDate startDate, LocalDate endDate);
 	
 	// payment mode wise data
 	@Query(value = ""
 	        + " SELECT "
 	        + "     data.payment_mode, "
 	        + "     SUM(data.amount) AS amount "
 	        + " FROM ( "
 	        + "     SELECT iph.payment_mode COLLATE utf8_unicode_ci AS payment_mode, "
 	        + "            SUM(iph.amount) AS amount "
 	        + "     FROM invoice_payment_history iph "
 	        + "     INNER JOIN invoice_master im ON iph.invoice_id = im.invoice_id "
 	        + "     WHERE :userId = 1 "
 	        + "       AND iph.is_delete = FALSE "
 	        + "       AND im.is_delete = FALSE "
 	        + "       AND (:startDate IS NULL OR iph.payment_date >= :startDate) "
 	        + "       AND (:endDate IS NULL OR iph.payment_date <= :endDate) "
 	        + "     GROUP BY iph.payment_mode "

 	        + " UNION ALL "

 	        + "     SELECT "
 	        + "         UPPER(ae.payment_mode) COLLATE utf8_unicode_ci AS payment_mode, "
 	        + "         SUM(ae.amount) AS amount "
 	        + "     FROM account_entry ae "
 	        + "     WHERE ae.is_delete = FALSE "
 	        + "       AND :userId = 1 "
 	        + "       AND ae.entry_type = 'RECEIPT' "
 	        + "       AND (:startDate IS NULL OR ae.date >= :startDate) "
 	        + "       AND (:endDate IS NULL OR ae.date <= :endDate) "
 	        + "     GROUP BY UPPER(ae.payment_mode) "

 	        + " UNION ALL "

 	        + "     SELECT "
 	        + "         CASE "
 	        + "             WHEN si.payment_mode = 'BANK TRANSFER' "
 	        + "                 THEN 'BANK_TRANSFER' "
 	        + "             ELSE UPPER(si.payment_mode) "
 	        + "         END COLLATE utf8_unicode_ci AS payment_mode, "
 	        + "         SUM(si.total_amount) AS amount "
 	        + "     FROM sales_invoice si "
 	        + "     INNER JOIN event_invoice ei "
 	        + "         ON si.invoice_no = ei.invoice_code "
 	        + "     WHERE (:userId != 1 AND ei.user_id = :userId) "
 	        + "       AND si.is_delete = FALSE "
 	        + "       AND ei.is_delete = FALSE "
 	        + "       AND (:startDate IS NULL OR DATE(si.payment_date) >= :startDate) "
 	        + "       AND (:endDate IS NULL OR DATE(si.payment_date) <= :endDate) "
 	        + "     GROUP BY "
 	        + "         CASE "
 	        + "             WHEN si.payment_mode = 'BANK TRANSFER' "
 	        + "                 THEN 'BANK_TRANSFER' "
 	        + "             ELSE UPPER(si.payment_mode) "
 	        + "         END "
 	        + " ) data "
 	        + " GROUP BY data.payment_mode",
 	        nativeQuery = true)
 	List<Object[]> getPaymentModeWiseAmount(
 	        @Param("startDate") LocalDate startDate,
 	        @Param("endDate") LocalDate endDate,
 	        @Param("userId") Long userId);
	
	// account ledger
	@Query(value = " "
			+ " SELECT"
			+ "    data.payment_date, "
			+ "    data.voucher_no, "
			+ "    '' AS account_name, "
			+ "    data.particular, "
			+ "    data.debit, "
			+ "    data.credit, "
			+ "    '' AS remarks "
			+ "FROM ("
			+ ""
			+ "    SELECT"
			+ "        0 AS sort_order,"
			+ "        CAST(:startDate AS DATE) AS payment_date,"
			+ "        '-' AS voucher_no,"
			+ "        CAST('OPB/PREV' AS CHAR) COLLATE utf8_unicode_ci AS particular,"
			+ "        IFNULL(CASE WHEN SUM(x.debit - x.credit) >= 0 THEN SUM(x.debit - x.credit) ELSE 0 END, 0) AS debit,"
			+ "        IFNULL(CASE WHEN SUM(x.debit - x.credit) <  0 THEN ABS(SUM(x.debit - x.credit)) ELSE 0 END, 0) AS credit"
			+ "    FROM ("
			+ "        SELECT"
			+ "            CAST(te.payment_date AS DATE) AS date,"
			+ "            0 AS debit,"
			+ "            te.amount AS credit"
			+ "        FROM trip_expense_payout_history te"
			+ "        INNER JOIN expenses e ON e.id = te.trip_expense_id"
			+ "        WHERE te.is_delete = FALSE"
			+ "          AND e.is_delete = FALSE"
			+ "          AND e.user_id = :userId "
			+ "          AND te.payment_date < CAST(:startDate AS DATE)"
			+ "          and e.account_contact_id = :accountContactId "
			+ ""
			+ "        UNION ALL"
			+ ""
			+ "        SELECT"
			+ "            CAST(op.payment_date AS DATE) AS date,"
			+ "            0 AS debit,"
			+ "            op.amount AS credit"
			+ "        FROM office_expense_payout_history op"
			+ "        INNER JOIN office_expenses oe ON op.office_expense_id = oe.id"
			+ "        WHERE op.is_delete = FALSE"
			+ "          AND oe.is_delete = FALSE"
			+ "          AND oe.user_id = :userId "
			+ "          AND op.payment_date < CAST(:startDate AS DATE)"
			+ "          AND oe.account_contact_id = :accountContactId "
			+ ""
			+ "        UNION ALL"
			+ ""
			+ "        SELECT"
			+ "            CAST(ae.date AS DATE) AS date,"
			+ "            CASE WHEN ae.entry_type = 'RECEIPT' THEN ae.amount ELSE 0 END AS debit,"
			+ "            CASE WHEN ae.entry_type = 'PAYMENT' THEN ae.amount ELSE 0 END AS credit"
			+ "        FROM account_entry ae"
			+ "        WHERE ae.is_delete = FALSE"
			+ "          AND :userId = 1"
			+ "          AND ae.date < CAST(:startDate AS DATE)"
			+ "          AND ae.account_contact_id = :accountContactId "
			+ ""
			+ "        UNION ALL"
			+ ""
			+ "        SELECT"
			+ "            CAST(vp.payment_date AS DATE) AS date,"
			+ "            COALESCE(vp.received_amount, 0) AS debit,"
			+ "            COALESCE(vp.pay_amount, 0) AS credit"
			+ "        FROM vendor_payments vp"
			+ "        WHERE vp.is_delete = FALSE"
			+ "          AND :userId != 1 "
			+ "          AND vp.user_id = :userId "
			+ "          AND vp.payment_date < CAST(:startDate AS DATE)"
			+ "          AND vp.vendor_id = :accountContactId and vp.vendor_cat = 'AccountContact'"
			+ "        "
			+ "        union all"
			+ "        "
			+ "        SELECT"
			+ "            CAST(:startDate AS DATE) AS DATE,"
			+ "            case "
			+ "					when ac.entry_type = 'RECEIPT'"
			+ "						then ac.opening_balance"
			+ "					else 0.00 end "
			+ "             as debit, "
			+ "            CASE "
			+ "					WHEN ac.entry_type = 'PAYMENT' "
			+ "						THEN ac.opening_balance "
			+ "				ELSE 0.00 END"
			+ "	     		as credit "
			+ "        FROM account_contact ac"
			+ "        where ac.account_contact_id = :accountContactId "
			+ "    ) x"
			+ ""
			+ "    UNION ALL"
			+ "    "
			+ "    SELECT"
			+ "        1 AS sort_order,"
			+ "        CAST(te.payment_date AS DATE) AS payment_date,"
			+ "        CAST('EXP' AS CHAR) COLLATE utf8_unicode_ci AS voucher_no,"
			+ "        CAST('TRIP EXPENSE' AS CHAR) COLLATE utf8_unicode_ci AS particular,"
			+ "        0 AS debit,"
			+ "        te.amount AS credit"
			+ "    FROM trip_expense_payout_history te"
			+ "    INNER JOIN expenses e ON te.trip_expense_id = e.id"
			+ "    WHERE te.is_delete = FALSE"
			+ "      AND e.is_delete = FALSE"
			+ "      AND e.user_id = :userId "
			+ "      AND te.payment_date >= CAST(:startDate AS DATE)"
			+ "      AND te.payment_date <= CAST(:endDate AS DATE)"
			+ "      AND e.account_contact_id = :accountContactId "
			+ ""
			+ "    UNION ALL"
			+ ""
			+ "    SELECT"
			+ "        1 AS sort_order,"
			+ "        CAST(op.payment_date AS DATE) AS payment_date,"
			+ "        CAST('EXP' AS CHAR) COLLATE utf8_unicode_ci AS voucher_no,"
			+ "        CAST(CONCAT(UPPER(iet.name), ' EXPENSE') AS CHAR) COLLATE utf8_unicode_ci AS particular,"
			+ "        0 AS debit,"
			+ "        op.amount AS credit"
			+ "    FROM office_expense_payout_history op"
			+ "    INNER JOIN office_expenses e ON op.office_expense_id = e.id"
			+ "    INNER JOIN income_expense_type iet ON iet.type_id = e.income_expense_type_id"
			+ "    WHERE op.is_delete = FALSE"
			+ "      AND e.is_delete = FALSE"
			+ "      AND e.user_id = :userId "
			+ "      AND op.payment_date >= CAST(:startDate AS DATE)"
			+ "      AND op.payment_date <= CAST(:endDate AS DATE)"
			+ "      AND e.account_contact_id = :accountContactId "
			+ ""
			+ "    UNION ALL"
			+ ""
			+ "    SELECT"
			+ "        1 AS sort_order,"
			+ "        CAST(ae.date AS DATE) AS payment_date,"
			+ "        CAST(ae.voucher_no AS CHAR) COLLATE utf8_unicode_ci AS voucher_no,"
			+ "        CAST('ACCOUNT ENTRY' AS CHAR) COLLATE utf8_unicode_ci AS particular,"
			+ "        CASE WHEN ae.entry_type = 'RECEIPT' THEN ae.amount ELSE 0 END AS debit,"
			+ "        CASE WHEN ae.entry_type = 'PAYMENT' THEN ae.amount ELSE 0 END AS credit"
			+ "    FROM account_entry ae"
			+ "    WHERE ae.is_delete = FALSE"
			+ "      AND :userId = 1 "
			+ "      AND ae.date >= CAST(:startDate AS DATE)"
			+ "      AND ae.date <= CAST(:endDate AS DATE)"
			+ "      AND ae.account_contact_id = :accountContactId "
			+ ""
			+ "    UNION ALL"
			+ ""
			+ "    SELECT"
			+ "        1 AS sort_order,"
			+ "        CAST(vp.payment_date AS DATE) AS payment_date,"
			+ "        CAST(vp.invoice_code AS CHAR) COLLATE utf8_unicode_ci AS voucher_no,"
			+ "        CAST('VENDOR PAYMENT' AS CHAR) COLLATE utf8_unicode_ci AS particular,"
			+ "        COALESCE(vp.received_amount, 0) AS debit,"
			+ "        COALESCE(vp.pay_amount, 0) AS credit"
			+ "    FROM vendor_payments vp"
			+ "    WHERE vp.is_delete = FALSE"
			+ "      AND vp.user_id = :userId "
			+ "      AND vp.payment_date >= CAST(:startDate AS DATE)"
			+ "      AND vp.payment_date <= CAST(:endDate AS DATE)"
			+ "      AND vp.vendor_id = :accountContactId and vendor_cat = 'AccountContact'"
			+ " ) data "
			+ " ORDER BY"
			+ "    data.sort_order ASC,"
			+ "    data.payment_date ASC ", nativeQuery = true)
	List<Object[]> getAccountLedgerByAccountContact(
			@Param("accountContactId") Long accountContactId,
			@Param("startDate") String startDate,
			@Param("endDate") String endDate,
			@Param("userId") Long userId);
}
