export const requiredFields = {
  basic_info: {
    client_id: "",
    meeting_date: "",
    status: "",
    event_type: "",
    budget: "",
    event_start_date: "",
    event_end_date: "",
    start_time: "",
    end_time: "",
    Venue_name: "",
    add_venue: "",
    remove_venue: "",
    notes: "",
    tentative_booking: "",
  },
  client_info: {
    title: "Mr.",
    name: "",
    address: "",
    mobile: "",
    highPriority: false,
    leadSource: "",
    client1Title: "Mr.",
    client1Name: "",
    client1Type: "groom",
    client1Address: "",
    client1Mobile: "",
    client2Title: "Mrs.",
    client2Name: "",
    client2Type: "bride",
    client2Address: "",
    client2Mobile: "",
  },
  functions: {
    function_array: [],
  },
  other: {
    groom_name: "",
    groom_family_name: "",
    groom_mobile: "",
    groom_instagram: "",
    groom_birth_date: null,
    bride_name: "",
    bride_family_name: "",
    bride_mobile: "",
    bride_instagram: "",
    bride_birth_date: null,
    Photographer_name: "",
    Photographer_mobile: "",
  },
};
