package com.crmportal.enums;

public enum FileType {

	// USER BASIC
	SALEFILE, MANAGERFILE, CALLFILE,

	// USER DOCUMENTS
	KYC, INVOICE, RECEIPT,

	// AMC / REFUND
	AMC_DOC, REFUND_DOC,

	// TEMPLATE / REPORT
	FRONT_PAGE, DETAILS_PAGE, WATERMARK, LAST_PAGE, NAMEPLATE_PAGE, CATEGORY_BG_PAGE, EXTRA_PAGE, NAMEPLATE_COVER_PAGE,
	
	//CHECKLIST
	
	LABOURFILE,
	
	VENUE_IMG,

	// COMMON
	IMAGE, DOC, OTHER;
}
