import { DataGridColumnHeader } from "@/components";
export const columns = [
  {
    accessorKey: "createdAt",
    header: ({ column }) => (
      <DataGridColumnHeader title="created At" column={column} />
    ),
  },
  {
    accessorKey: "first_name",
    header: ({ column }) => (
      <DataGridColumnHeader title="Contact Name" column={column} />
    ),
  },
  {
    accessorKey: "mobile",
    header: ({ column }) => (
      <DataGridColumnHeader title="Mobile" column={column} />
    ),
  },
  {
    accessorKey: "company",
    header: ({ column }) => (
      <DataGridColumnHeader title="company" column={column} />
    ),
  },
  {
    accessorKey: "upcomingfollowup",
    header: ({ column }) => (
      <DataGridColumnHeader title="Up Coming Follow-up" column={column} />
    ),
  },
  {
    accessorKey: "lastfollowup",
    header: ({ column }) => (
      <DataGridColumnHeader title="Last Follow-up" column={column} />
    ),
  },
  {
    accessorKey: "tag",
    header: ({ column }) => (
      <DataGridColumnHeader title="Tag" column={column} />
    ),
  },
  {
    accessorKey: "action",
    header: "Action",
    cell: ({ cell }) => {
      return cell.row.original.action;
    },
  },
];
export const defaultData = [
  {
    id: 1,
    createdAt: "1942-04-12",
    first_name: "Tiger Nixon",
    mobile: "9865326598",
    company: "Edinburgh",
    upcomingfollowup: "--",
    lastfollowup: "--",
    tag: "test",
  },
  {
    id: 2,
    createdAt: "1942-04-12",
    first_name: "Garrett Winters",
    mobile: "9865326598",
    company: "Tokyo",
    upcomingfollowup: "--",
    lastfollowup: "--",
    tag: "test",
  },
  {
    id: 3,
    createdAt: "1942-04-12",
    first_name: "Ashton Cox",
    mobile: "9865326598",
    company: "San Francisco",
    upcomingfollowup: "--",
    lastfollowup: "--",
    tag: "test",
  },
  {
    id: 4,
    createdAt: "1942-04-12",
    first_name: "Airi Satou",
    mobile: "9865326598",
    company: "Tokyo",
    upcomingfollowup: "--",
    lastfollowup: "--",
    tag: "test",
  },
  {
    id: 5,
    createdAt: "1942-04-12",
    first_name: "Brielle Williamson",
    mobile: "9865326598",
    company: "New York",
    upcomingfollowup: "--",
    lastfollowup: "--",
    tag: "test",
  },
  {
    id: 6,
    createdAt: "1942-04-12",
    first_name: "Herrod Chandler",
    mobile: "9865326598",
    company: "San Francisco",
    upcomingfollowup: "--",
    lastfollowup: "--",
    tag: "test",
  },
  {
    id: 7,
    createdAt: "1942-04-12",
    first_name: "Rhona Davidson",
    mobile: "9865326598",
    company: "Tokyo",
    upcomingfollowup: "--",
    lastfollowup: "--",
    tag: "test",
  },
  {
    id: 8,
    createdAt: "1942-04-12",
    first_name: "Colleen Hurst",
    mobile: "9865326598",
    company: "San Francisco",
    upcomingfollowup: "--",
    lastfollowup: "--",
    tag: "test",
  },
  {
    id: 9,
    createdAt: "1942-04-12",
    first_name: "Sonya Frost",
    mobile: "9865326598",
    company: "Edinburgh",
    upcomingfollowup: "--",
    lastfollowup: "--",
    tag: "test",
  },
  {
    id: 10,
    createdAt: "1942-04-12",
    first_name: "Jena Gaines",
    mobile: "9865326598",
    company: "London",
    upcomingfollowup: "--",
    lastfollowup: "--",
    tag: "test",
  },
  {
    id: 11,
    createdAt: "1942-04-12",
    first_name: "Quinn Flynn",
    mobile: "9865326598",
    company: "Edinburgh",
    upcomingfollowup: "--",
    lastfollowup: "--",
    tag: "test",
  },
  {
    id: 12,
    createdAt: "1942-04-12",
    first_name: "Charde Marshall",
    mobile: "9865326598",
    company: "San Francisco",
    upcomingfollowup: "--",
    lastfollowup: "--",
    tag: "test",
  },
  {
    id: 13,
    createdAt: "1942-04-12",
    first_name: "Haley Kennedy",
    mobile: "9865326598",
    company: "London",
    upcomingfollowup: "--",
    lastfollowup: "--",
    tag: "test",
  },
  {
    id: 14,
    createdAt: "1942-04-12",
    first_name: "Tatyana Fitzpatrick",
    mobile: "9865326598",
    company: "London",
    upcomingfollowup: "--",
    lastfollowup: "--",
    tag: "test",
  },
  {
    id: 15,
    createdAt: "1942-04-12",
    first_name: "Michael Silva",
    mobile: "9865326598",
    company: "London",
    upcomingfollowup: "--",
    lastfollowup: "--",
    tag: "test",
  },
  {
    id: 16,
    createdAt: "1942-04-12",
    first_name: "Paul Byrd",
    mobile: "9865326598",
    company: "New York",
    upcomingfollowup: "--",
    lastfollowup: "--",
    tag: "test",
  },
  {
    id: 17,
    createdAt: "1942-04-12",
    first_name: "Gloria Little",
    mobile: "9865326598",
    company: "New York",
    upcomingfollowup: "--",
    lastfollowup: "--",
    tag: "test",
  },
  {
    id: 18,
    createdAt: "1942-04-12",
    first_name: "Bradley Greer",
    mobile: "9865326598",
    company: "London",
    upcomingfollowup: "--",
    lastfollowup: "--",
    tag: "test",
  },
  {
    id: 19,
    createdAt: "1942-04-12",
    first_name: "Dai Rios",
    mobile: "9865326598",
    company: "Edinburgh",
    upcomingfollowup: "--",
    lastfollowup: "--",
    tag: "test",
  },
  {
    id: 20,
    createdAt: "1942-04-12",
    first_name: "Jenette Caldwell",
    mobile: "9865326598",
    company: "New York",
    upcomingfollowup: "--",
    lastfollowup: "--",
    tag: "test",
  },
  {
    id: 21,
    createdAt: "1942-04-12",
    first_name: "Yuri Berry",
    mobile: "9865326598",
    company: "New York",
    upcomingfollowup: "--",
    lastfollowup: "--",
    tag: "test",
  },
  {
    id: 22,
    createdAt: "1942-04-12",
    first_name: "Caesar Vance",
    mobile: "9865326598",
    company: "New York",
    upcomingfollowup: "--",
    lastfollowup: "--",
    tag: "test",
  },
  {
    id: 23,
    createdAt: "1942-04-12",
    first_name: "Doris Wilder",
    mobile: "9865326598",
    company: "Sydney",
    upcomingfollowup: "--",
    lastfollowup: "--",
    tag: "test",
  },
  {
    id: 24,
    createdAt: "1942-04-12",
    first_name: "Angelica Ramos",
    mobile: "9865326598",
    company: "London",
    upcomingfollowup: "--",
    lastfollowup: "--",
    tag: "test",
  },
  {
    id: 25,
    createdAt: "1942-04-12",
    first_name: "Gavin Joyce",
    mobile: "9865326598",
    company: "Edinburgh",
    upcomingfollowup: "--",
    lastfollowup: "--",
    tag: "test",
  },
  {
    id: 26,
    createdAt: "1942-04-12",
    first_name: "Jennifer Chang",
    mobile: "9865326598",
    company: "Singapore",
    upcomingfollowup: "--",
    lastfollowup: "--",
    tag: "test",
  },
  {
    id: 27,
    createdAt: "1942-04-12",
    first_name: "Brenden Wagner",
    mobile: "9865326598",
    company: "San Francisco",
    upcomingfollowup: "--",
    lastfollowup: "--",
    tag: "test",
  },
  {
    id: 28,
    createdAt: "1942-04-12",
    first_name: "Fiona Green",
    mobile: "9865326598",
    company: "San Francisco",
    upcomingfollowup: "--",
    lastfollowup: "--",
    tag: "test",
  },
  {
    id: 29,
    createdAt: "1942-04-12",
    first_name: "Shou Itou",
    mobile: "9865326598",
    company: "Tokyo",
    upcomingfollowup: "--",
    lastfollowup: "--",
    tag: "test",
  },
  {
    id: 30,
    createdAt: "1942-04-12",
    first_name: "Michelle House",
    mobile: "9865326598",
    company: "Sidney",
    upcomingfollowup: "--",
    lastfollowup: "--",
    tag: "test",
  },

  {
    id: 31,
    createdAt: "1942-04-12",
    first_name: "Suki Burks",
    mobile: "9865326598",
    company: "London",
    upcomingfollowup: "--",
    lastfollowup: "--",
    tag: "test",
  },
  {
    id: 32,
    createdAt: "1942-04-12",
    first_name: "Prescott Bartlett",
    mobile: "9865326598",
    company: "London",
    upcomingfollowup: "--",
    lastfollowup: "--",
    tag: "test",
  },
  {
    id: 33,
    createdAt: "1942-04-12",
    first_name: "Gavin Cortez",
    mobile: "9865326598",
    company: "San Francisco",
    upcomingfollowup: "--",
    lastfollowup: "--",
    tag: "test",
  },
  {
    id: 34,
    createdAt: "1942-04-12",
    first_name: "Martena Mccray",
    mobile: "9865326598",
    company: "Edinburgh",
    upcomingfollowup: "--",
    lastfollowup: "--",
    tag: "test",
  },
  {
    id: 35,
    createdAt: "1942-04-12",
    first_name: "Unity Butler",
    mobile: "9865326598",
    company: "San Francisco",
    upcomingfollowup: "--",
    lastfollowup: "--",
    tag: "test",
  },
];
